# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-23 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset1',
            fields=[
                ('kode_field', models.IntegerField(primary_key='True', serialize=False, unique='true')),
                ('nama_field', models.CharField(max_length=100, null='False')),
                ('Gas_Target', models.FloatField(null='False')),
                ('Oil_Target', models.FloatField(null='False')),
                ('OilUOM', models.CharField(default='BOpd', max_length=10, null='False')),
                ('GasUOM', models.CharField(default='MMSCFD', max_length=10, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='Asset2',
            fields=[
                ('kode_field', models.IntegerField(primary_key='True', serialize=False, unique='true')),
                ('nama_field', models.CharField(max_length=100, null='False')),
                ('Gas_Target', models.FloatField(null='False')),
                ('Oil_Target', models.FloatField(null='False')),
                ('OilUOM', models.CharField(default='BOpd', max_length=10, null='False')),
                ('GasUOM', models.CharField(default='MMSCFD', max_length=10, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='Asset3',
            fields=[
                ('kode_field', models.IntegerField(primary_key='True', serialize=False, unique='true')),
                ('nama_field', models.CharField(max_length=100, null='False')),
                ('Gas_Target', models.FloatField(null='False')),
                ('Oil_Target', models.FloatField(null='False')),
                ('OilUOM', models.CharField(default='BOpd', max_length=10, null='False')),
                ('GasUOM', models.CharField(default='MMSCFD', max_length=10, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='Asset4',
            fields=[
                ('kode_field', models.IntegerField(primary_key='True', serialize=False, unique='true')),
                ('nama_field', models.CharField(max_length=100, null='False')),
                ('Gas_Target', models.FloatField(null='False')),
                ('Oil_Target', models.FloatField(null='False')),
                ('OilUOM', models.CharField(default='BOpd', max_length=10, null='False')),
                ('GasUOM', models.CharField(default='MMSCFD', max_length=10, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='Asset5',
            fields=[
                ('kode_field', models.IntegerField(primary_key='True', serialize=False, unique='true')),
                ('nama_field', models.CharField(max_length=100, null='False')),
                ('Gas_Target', models.FloatField(null='False')),
                ('Oil_Target', models.FloatField(null='False')),
                ('OilUOM', models.CharField(default='BOpd', max_length=10, null='False')),
                ('GasUOM', models.CharField(default='MMSCFD', max_length=10, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='Input_Asset1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null='False', verbose_name='date published')),
                ('nama_field', models.CharField(max_length=100, null='False')),
                ('Gas_Target', models.FloatField(null='False')),
                ('Oil_Target', models.FloatField(null='False')),
                ('InputOil_Target', models.FloatField(null='False')),
                ('InputGas_Target', models.FloatField(null='False')),
                ('OilUOM', models.CharField(default='BOpd', max_length=10, null='False')),
                ('GasUOM', models.CharField(default='MMSCFD', max_length=10, null='False')),
                ('id_Kode_field', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='ProductionP.Asset1')),
            ],
        ),
        migrations.CreateModel(
            name='Input_Asset2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null='False', verbose_name='date published')),
                ('nama_field', models.CharField(max_length=100, null='False')),
                ('Gas_Target', models.FloatField(null='False')),
                ('Oil_Target', models.FloatField(null='False')),
                ('InputOil_Target', models.FloatField(null='False')),
                ('InputGas_Target', models.FloatField(null='False')),
                ('OilUOM', models.CharField(default='BOpd', max_length=10, null='False')),
                ('GasUOM', models.CharField(default='MMSCFD', max_length=10, null='False')),
                ('id_Kode_field', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='ProductionP.Asset2')),
            ],
        ),
        migrations.CreateModel(
            name='Input_Asset3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null='False', verbose_name='date published')),
                ('nama_field', models.CharField(max_length=100, null='False')),
                ('Gas_Target', models.FloatField(null='False')),
                ('Oil_Target', models.FloatField(null='False')),
                ('InputOil_Target', models.FloatField(null='False')),
                ('InputGas_Target', models.FloatField(null='False')),
                ('OilUOM', models.CharField(default='BOpd', max_length=10, null='False')),
                ('GasUOM', models.CharField(default='MMSCFD', max_length=10, null='False')),
                ('id_Kode_field', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='ProductionP.Asset3')),
            ],
        ),
        migrations.CreateModel(
            name='Input_Asset4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null='False', verbose_name='date published')),
                ('nama_field', models.CharField(max_length=100, null='False')),
                ('Gas_Target', models.FloatField(null='False')),
                ('Oil_Target', models.FloatField(null='False')),
                ('InputOil_Target', models.FloatField(null='False')),
                ('InputGas_Target', models.FloatField(null='False')),
                ('OilUOM', models.CharField(default='BOpd', max_length=10, null='False')),
                ('GasUOM', models.CharField(default='MMSCFD', max_length=10, null='False')),
                ('id_Kode_field', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='ProductionP.Asset4')),
            ],
        ),
        migrations.CreateModel(
            name='Input_Asset5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null='False', verbose_name='date published')),
                ('nama_field', models.CharField(max_length=100, null='False')),
                ('Gas_Target', models.FloatField(null='False')),
                ('Oil_Target', models.FloatField(null='False')),
                ('InputOil_Target', models.FloatField(null='False')),
                ('InputGas_Target', models.FloatField(null='False')),
                ('OilUOM', models.CharField(default='BOpd', max_length=10, null='False')),
                ('GasUOM', models.CharField(default='MMSCFD', max_length=10, null='False')),
                ('id_Kode_field', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='ProductionP.Asset5')),
            ],
        ),
    ]
